### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by tdelesio** [Tyzer34/plexMusicPlayer#6]
I ended up forking your code base mostly because I wanted to change the intents.  I fixed a couple bugs in the methods.py when tracks, artists, and albums return multiple results.  I just take the first one in the list and send it on its way.  Here is the link if you want to see the code.  I can push to your repo too if you would like. 

https://github.com/tdelesio/plexMusicPlayer/blob/master/plexmusicplayer/methods.py

I also added two separate intents.  From my testing, it seamed that the intents were getting confused.  I would be asking for a track and/or album, and amazon thought I was looking for an artist.  To try and make it less confused I added two more intents.  Is there a better way to test this locally?  I have been pushing to herkou everything but it is slow.  I launched the server.py file locally and tried to post the json from the service simulator, but it gave me some token error (not the environment variables token).

**Comment by Tyzer34** [comment]
It would be great if you wanted to help out with the project!
Have you committed your changes yet? In you latest commit, I only see the logger being added.
There is a better way to test locally! If you run _server.py_ locally, it will be hosted on _localhost:5000_. Next, you can use **ngrok** to forward port 5000 to an external ip, which you can then link to your Alexa Skill. (command for ngrok would be _ngrok http 5000_)

**Comment by tdelesio** [comment]
I guess I didn't. It's there now.  Check it out and let me know.

**Comment by Tyzer34** [comment]
I saw your update! Seems great to me! I've added your changes to the current project! Thank you!

**Comment by tdelesio** [comment]
Yea if you make me a contributor, I will switch my code base back to yours and commit there going forward.  I also changed some of the Intents which you may or may not like.  I can keep those separate however

**Comment by Tyzer34** [comment]
No problem, I'm glad you want to contribute! I would advise you though to make a separate private repository that contains a clone of this one. You can then use that private testing repository for trying out stuff. If you have something working, you can push the changed files to this public repository! This is just to keep the commits here clean and clear :)

**Comment by tdelesio** [comment]
Yea I forked it.  I'll push my changes there first and then commit back to your repo.
